---
- hosts: all
  vars:
    - user_password: 'MySecretPassword'
  gather_facts: no
  become: yes
  become_method: sudo
  tasks:
  - name: Add a new user
    user:
      name: "{{ user }}"
      shell: /bin/bash
      password: "{{ user_password }}"
  - name: Add new user to the sudoers
    copy:
      dest: "/etc/sudoers.d/'{{ user }}'"
      content: "'{{ user }}'  ALL=(ALL)  NOPASSWD: ALL"
  - name: Deploy SSH Key
    authorized_key: user='{{ user }}'
                    key="{{ lookup('file', '/home/'{{ user }}'/.ssh/id_rsa.pub') }}"
                    state=present
  - name: Disable Password Authentication
    lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes
  - name: Disable Root Login
    lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
    notify:
         - restart ssh
  handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted
